import type { DriveFile, DriveFolder } from "~/types/drive";

export const folderIds = {
  root: 1,
  projects: 2,
  documents: 3,
  photos: 4,
  archives: 5,
  webDev: 6,
  mobile: 7,
  design: 8,
  vacation: 9,
  family: 10,
} as const;

export const mockFolders: DriveFolder[] = [
  {
    id: folderIds.root,
    name: "Root",
    type: "folder",
    modified: "Dec 20, 2024",
    parent: null,
  },
  // Root level folders
  {
    id: folderIds.projects,
    name: "Projects",
    type: "folder",
    modified: "Dec 25, 2024",
    parent: folderIds.root,
  },
  {
    id: folderIds.documents,
    name: "Documents",
    type: "folder",
    modified: "Dec 24, 2024",
    parent: folderIds.root,
  },
  {
    id: folderIds.photos,
    name: "Photos",
    type: "folder",
    modified: "Dec 22, 2024",
    parent: folderIds.root,
  },
  {
    id: folderIds.archives,
    name: "Archives",
    type: "folder",
    modified: "Nov 15, 2024",
    parent: folderIds.root,
  },
  // Projects subfolders
  {
    id: folderIds.webDev,
    name: "Web Development",
    type: "folder",
    modified: "Dec 25, 2024",
    parent: folderIds.projects,
  },
  {
    id: folderIds.mobile,
    name: "Mobile Apps",
    type: "folder",
    modified: "Dec 18, 2024",
    parent: folderIds.projects,
  },
  {
    id: folderIds.design,
    name: "Design Files",
    type: "folder",
    modified: "Dec 10, 2024",
    parent: folderIds.projects,
  },
  // Photos subfolders
  {
    id: folderIds.vacation,
    name: "Vacation 2024",
    type: "folder",
    modified: "Dec 22, 2024",
    parent: folderIds.photos,
  },
  {
    id: folderIds.family,
    name: "Family Photos",
    type: "folder",
    modified: "Dec 15, 2024",
    parent: folderIds.photos,
  },
];

export const mockFiles: DriveFile[] = [
  // Root level files
  {
    id: 101,
    name: "README.md",
    type: "file",
    size: 2458,
    modified: "Dec 26, 2024",
    fileUrl: "https://example.com/readme.md",
    parent: folderIds.root,
  },
  {
    id: 102,
    name: "Quick Notes.txt",
    type: "file",
    size: 1229,
    modified: "Dec 25, 2024",
    fileUrl: "https://example.com/notes.txt",
    parent: folderIds.root,
  },
  // Documents folder files
  {
    id: 103,
    name: "Resume_2024.pdf",
    type: "file",
    size: 250880,
    modified: "Dec 24, 2024",
    fileUrl: "https://example.com/resume.pdf",
    parent: folderIds.documents,
  },
  {
    id: 104,
    name: "Cover_Letter.docx",
    type: "file",
    size: 89088,
    modified: "Dec 23, 2024",
    fileUrl: "https://example.com/cover.docx",
    parent: folderIds.documents,
  },
  {
    id: 105,
    name: "Budget_2024.xlsx",
    type: "file",
    size: 159744,
    modified: "Dec 20, 2024",
    fileUrl: "https://example.com/budget.xlsx",
    parent: folderIds.documents,
  },
  {
    id: 106,
    name: "Q4_Presentation.pptx",
    type: "file",
    size: 3355443,
    modified: "Dec 18, 2024",
    fileUrl: "https://example.com/presentation.pptx",
    parent: folderIds.documents,
  },
  // Web Development folder files
  {
    id: 107,
    name: "portfolio-design.fig",
    type: "file",
    size: 5033165,
    modified: "Dec 25, 2024",
    fileUrl: "https://example.com/portfolio.fig",
    parent: folderIds.webDev,
  },
  {
    id: 108,
    name: "API_Documentation.pdf",
    type: "file",
    size: 913408,
    modified: "Dec 24, 2024",
    fileUrl: "https://example.com/api-docs.pdf",
    parent: folderIds.webDev,
  },
  {
    id: 109,
    name: "wireframes_v2.sketch",
    type: "file",
    size: 2202010,
    modified: "Dec 22, 2024",
    fileUrl: "https://example.com/wireframes.sketch",
    parent: folderIds.webDev,
  },
  {
    id: 110,
    name: "homepage_mockup.psd",
    type: "file",
    size: 16357786,
    modified: "Dec 20, 2024",
    fileUrl: "https://example.com/mockup.psd",
    parent: folderIds.webDev,
  },
  // Mobile Apps folder files
  {
    id: 111,
    name: "app_icon.png",
    type: "file",
    size: 131072,
    modified: "Dec 18, 2024",
    fileUrl: "https://example.com/app-icon.png",
    parent: folderIds.mobile,
  },
  {
    id: 112,
    name: "splash_screen.png",
    type: "file",
    size: 466944,
    modified: "Dec 17, 2024",
    fileUrl: "https://example.com/splash.png",
    parent: folderIds.mobile,
  },
  {
    id: 113,
    name: "app_v1.2.3.apk",
    type: "file",
    size: 29779558,
    modified: "Dec 15, 2024",
    fileUrl: "https://example.com/app.apk",
    parent: folderIds.mobile,
  },
  // Design Files folder files
  {
    id: 114,
    name: "company_logo.svg",
    type: "file",
    size: 46080,
    modified: "Dec 10, 2024",
    fileUrl: "https://example.com/logo.svg",
    parent: folderIds.design,
  },
  {
    id: 115,
    name: "Brand_Guidelines.pdf",
    type: "file",
    size: 5872026,
    modified: "Dec 8, 2024",
    fileUrl: "https://example.com/brand.pdf",
    parent: folderIds.design,
  },
  {
    id: 116,
    name: "color_palette.ase",
    type: "file",
    size: 12288,
    modified: "Dec 5, 2024",
    fileUrl: "https://example.com/colors.ase",
    parent: folderIds.design,
  },
  // Vacation Photos folder files
  {
    id: 117,
    name: "beach_sunset.jpg",
    type: "file",
    size: 3355443,
    modified: "Dec 22, 2024",
    fileUrl: "https://example.com/beach1.jpg",
    parent: folderIds.vacation,
  },
  {
    id: 118,
    name: "ocean_view.jpg",
    type: "file",
    size: 2936013,
    modified: "Dec 22, 2024",
    fileUrl: "https://example.com/beach2.jpg",
    parent: folderIds.vacation,
  },
  {
    id: 119,
    name: "mountain_hike.jpg",
    type: "file",
    size: 4299162,
    modified: "Dec 21, 2024",
    fileUrl: "https://example.com/mountain.jpg",
    parent: folderIds.vacation,
  },
  {
    id: 120,
    name: "city_lights.jpg",
    type: "file",
    size: 3670016,
    modified: "Dec 20, 2024",
    fileUrl: "https://example.com/city.jpg",
    parent: folderIds.vacation,
  },
  // Family Photos folder files
  {
    id: 121,
    name: "christmas_2024.jpg",
    type: "file",
    size: 3040870,
    modified: "Dec 15, 2024",
    fileUrl: "https://example.com/christmas.jpg",
    parent: folderIds.family,
  },
  {
    id: 122,
    name: "birthday_party.jpg",
    type: "file",
    size: 3250586,
    modified: "Nov 28, 2024",
    fileUrl: "https://example.com/birthday.jpg",
    parent: folderIds.family,
  },
  {
    id: 123,
    name: "thanksgiving.jpg",
    type: "file",
    size: 2831155,
    modified: "Nov 24, 2024",
    fileUrl: "https://example.com/thanksgiving.jpg",
    parent: folderIds.family,
  },
  // Archives folder files
  {
    id: 124,
    name: "backup_2024.zip",
    type: "file",
    size: 1288490189,
    modified: "Nov 15, 2024",
    fileUrl: "https://example.com/backup.zip",
    parent: folderIds.archives,
  },
  {
    id: 125,
    name: "old_project_files.rar",
    type: "file",
    size: 897581056,
    modified: "Oct 20, 2024",
    fileUrl: "https://example.com/old-project.rar",
    parent: folderIds.archives,
  },
  {
    id: 126,
    name: "archive_2023.7z",
    type: "file",
    size: 2576980378,
    modified: "Jan 5, 2024",
    fileUrl: "https://example.com/archive.7z",
    parent: folderIds.archives,
  },
];
